version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: pos_tech_postgres
    environment:
      POSTGRES_USER: pos_tech
      POSTGRES_PASSWORD: pos_tech
      POSTGRES_DB: tech_challenge_01
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
    name: pos_tech_postgres_data